spring.application.name=BlogApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/BloggingApp
spring.datasource.username=postgres
spring.datasource.password=mushraf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect